### ISSUE TITLE
Doesn't work if no rowid

### ISSUE THREAD

**Issue by frabcus** [scraperwiki/odata-cgi#5]
For a Table Xtract dragon "relational table making" branch of this PDF http://www.nhlbi.nih.gov/guidelines/obesity/bmi_tbl.pdf

Dataset: https://scraperwiki.com/dataset/y0roelv/view/btijdvp

```
Traceback (most recent call last):
  File "/usr/lib/python3.3/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.3/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/usr/local/lib/python3.3/dist-packages/werkzeug/wsgi.py", line 682, in __next__
    return self._next()
  File "/usr/local/lib/python3.3/dist-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/tools/global-cgi/cgi-bin/odata/default", line 191, in build_odata
    record_count_total, offset, limit, skip_token)
  File "/tools/global-cgi/cgi-bin/odata/default", line 157, in render
    rowid=entry['rowid'],
  File "/usr/local/lib/python3.3/dist-packages/sqlalchemy/engine/result.py", line 332, in _key_fallback
    expression._string_or_unprintable(key))
sqlalchemy.exc.NoSuchColumnError: "Could not locate column in row for column 'rowid'"
```

**Comment by frabcus** [comment]
This happens with any table with an `id` column, and only with such tables.

Some confusion in SQLAlchemy/Sqlite between `rowid` and `id`?

**Comment by pwaller** [comment]
http://docs.sqlalchemy.org/en/rel_0_7/dialects/sqlite.html#auto-incrementing-behavior

**Comment by frabcus** [comment]
When you "SELECT rowid" in SQLite for a database with a unique id column, it whimsically returns that. This with headers on so you can see:

```
sqlite> SELECT rowid, _sources.id AS _sources_id, _sources.checksum AS _sources_checksum, _sources.extension AS _sources_extension, _sources.last_read AS _sources_last_read, _sources.headers AS _sources_headers, _sources.url AS _sources_url, _sources.filename AS _sources_filename, _sources.extracted AS _sources_extracted, _sources.first_read AS _sources_first_read, _sources.total_grids AS _sources_total_grids from _sources;
id|_sources_id|_sources_checksum|_sources_extension|_sources_last_read|_sources_headers|_sources_url|_sources_filename|_sources_extracted|_sources_first_read|_sources_total_grids
1|1|8fe5bf82efd50976e0a246992720b872|pdf|2014-07-08 09:22:36.862581|{"content-length": "34814", "accept-ranges": "bytes", "server": "Apache/2.2.12 (Linux/SUSE)", "last-modified": "Mon, 14 Apr 2014 17:20:29 GMT", "connection": "keep-alive", "etag": "\"1ce83f-87fe-4f703e6623140\"", "date": "Tue, 08 Jul 2014 09:22:39 GMT", "p3p": "CP=\"IDC DSP COR CUR TAIi PSAi PSDi IVAi OUR NOR PRE\"", "content-type": "application/pdf"}|http://www.nhlbi.nih.gov/guidelines/obesity/bmi_tbl.pdf|http/sources/8fe5bf82efd50976e0a246992720b872|1|2014-07-08 09:22:36.862538|1
```
